---
- name: check hostname
  command: hostnamectl status
  register: hostnamectl_result
  check_mode: no
  changed_when: false

- name: change hostname
  command: hostnamectl set-hostname '{{ hostname_fqdn }}'
  when: "(hostname_fqdn) not in hostnamectl_result.stdout"

- name: install apache2
  apt:
    name: apache2

- name: gather package facts
  package_facts:

- name: start and enable apache2
  service:
    name: apache2
    state: started
    enabled: yes
  when: "'apache2' in ansible_facts.packages"

- name: open port http and https
  ufw:
    rule: allow
    proto: tcp
    from: 0.0.0.0/0
    port: '{{ item }}'
  loop:
    - 80
    - 443
